/*************************************************************************\
 * messages.h
 *
 * Simple header file which defines all user messages.
 * (C) 94   Ralf Seidel
 *          WÅlfrather Str. 45
 *          42105 Wuppertal
 *          email: seidel3@wrcs1.uni-wuppertal.de
 *
 * Set tabs to 3 to get a readable source.
\*************************************************************************/

#define MYM_STARTTHREAD		(WM_USER + 1)
#define MYM_ENDTHREAD		(WM_USER + 2)
#define MYM_OPTIONSCHANGED	(WM_USER + 3)
#define MYM_ISRUNNING		(WM_USER + 4)
#define MYM_KILLTHREAD		(WM_USER + 5)
#define MYM_SUSPEND			(WM_USER + 6)
#define MYM_RESUME			(WM_USER + 7)
#define MYM_SETCUTOPT		(WM_USER + 8)
#define MYM_SETSELECT		(WM_USER + 9)
#define MYM_UNSELECT			(WM_USER + 10)
#define MYM_UPDATECELL		(WM_USER + 11)

